"""fix created_at server_default

Revision ID: 7597dac23898
Revises: f590e2fbeff8
Create Date: 2026-05-16 21:02:50.620197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7597dac23898'
down_revision: Union[str, Sequence[str], None] = 'f590e2fbeff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('reminder_time', sa.Time(), nullable=False))
    op.drop_column('reminders', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('reminders', 'reminder_time')
    # ### end Alembic commands ###
