"""fix user_id

Revision ID: 9af05bc714df
Revises: 7597dac23898
Create Date: 2026-05-17 11:22:51.924991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af05bc714df'
down_revision: Union[str, Sequence[str], None] = '7597dac23898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_column('habits', 'user_id')
    # ### end Alembic commands ###
