"""fix user and habit

Revision ID: bf6a5dcc8d8e
Revises: 9af05bc714df
Create Date: 2026-05-17 11:33:14.324359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6a5dcc8d8e'
down_revision: Union[str, Sequence[str], None] = '9af05bc714df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('habits_user_id_fkey'), 'habits', type_='foreignkey')
    op.drop_column('habits', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('habits_user_id_fkey'), 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
