"""add user habit entry reminder tables

Revision ID: f590e2fbeff8
Revises: b057e8203327
Create Date: 2026-05-16 20:39:44.606232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f590e2fbeff8'
down_revision: Union[str, Sequence[str], None] = 'b057e8203327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'completed_at')
    )
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('days', postgresql.ARRAY(sa.INTEGER()), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_table('entries')
    op.drop_table('users')
    # ### end Alembic commands ###
